---
# For my dev environment only
version: "3"
services:
  motionui:
    container_name: motionui-dev
    image: motionui-image
    privileged: true
    network_mode: host
    environment:
      FQDN: motionui-dev.localhost
    build:
      context: .
      dockerfile: Dockerfile
      args:
        branch: devel
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/docker/volumes/motionui-dev-data:/var/lib/motionui
      - /var/lib/docker/volumes/motionui-dev-captures:/var/lib/motion
      - /var/lib/docker/volumes/motionui-dev-logs:/var/log/nginx
      - /var/lib/docker/volumes/motionui-dev-www:/var/www/motionui
